/**
 * Official 46 Delhi Wards from DSGMC Election with Candidates, Phones, and Addresses
 */

const DELHI_HEAD_OFFICE = {
  id: 'del-ho-001',
  name: 'Delhi Head Office',
  code: 'DEL-HO',
  city: 'New Delhi',
  state: 'Delhi',
};

const NOIDA_HEAD_OFFICE = {
  id: 'noi-ho-002',
  name: 'Noida Head Office',
  code: 'NOI-HO',
  city: 'Noida',
  state: 'Uttar Pradesh',
};

const GURGAON_HEAD_OFFICE = {
  id: 'ggn-ho-003',
  name: 'Gurgaon Head Office',
  code: 'GGN-HO',
  city: 'Gurugram',
  state: 'Haryana',
};

const ALL_HEAD_OFFICES = [DELHI_HEAD_OFFICE, NOIDA_HEAD_OFFICE, GURGAON_HEAD_OFFICE];

const ALL_WARDS = [
  // Delhi Wards 1 to 46 from candidate PDF
  {
    id: 'ward-del-01',
    head_office_id: 'del-ho-001',
    ward_no: 1,
    name: 'Rohini',
    code: 'DEL-WD-01',
    contact_person: 'S. Sarvjit Singh Virk',
    phone: '9811695785',
    address: '165, Farmers Apartment, Plot no.8, Sector-13, Rohini Delhi-110085',
    ward_area: 'North West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-02',
    head_office_id: 'del-ho-001',
    ward_no: 2,
    name: 'Saroop Nagar',
    code: 'DEL-WD-02',
    contact_person: 'S. Sukhbir Singh Kalra',
    phone: '9810014786',
    address: 'Saroop Nagar, North Delhi',
    ward_area: 'North Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-03',
    head_office_id: 'del-ho-001',
    ward_no: 3,
    name: 'Civil Line',
    code: 'DEL-WD-03',
    contact_person: 'S. Jasbir Singh Jassi',
    phone: '9818711003',
    address: '276A, 3rd Floor, Indira Vihar, Kingsway Camp, Dr. Mukherjee Nagar, Delhi-110009',
    ward_area: 'North Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-04',
    head_office_id: 'del-ho-001',
    ward_no: 4,
    name: 'Pitam Pura',
    code: 'DEL-WD-04',
    contact_person: 'S. Mohinderpal Singh Chadha',
    phone: '9811048221',
    address: 'MD-26, Vishakha Enclave, Pitampura, Delhi-110088',
    ward_area: 'North West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-05',
    head_office_id: 'del-ho-001',
    ward_no: 5,
    name: 'Model Town',
    code: 'DEL-WD-05',
    contact_person: 'S. Amritpal Singh (Palco)',
    phone: '9899598009',
    address: 'B-2, Panchvati Azadpur, Delhi-110033',
    ward_area: 'North Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-06',
    head_office_id: 'del-ho-001',
    ward_no: 6,
    name: 'Shakti Nagar',
    code: 'DEL-WD-06',
    contact_person: 'S. Harvinder Singh K. P.',
    phone: '9811198009',
    address: 'B-2, Panchvati, Opp. Azadpur Subzi Mandi, Delhi-110033',
    ward_area: 'North Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-07',
    head_office_id: 'del-ho-001',
    ward_no: 7,
    name: 'Tri Nagar',
    code: 'DEL-WD-07',
    contact_person: 'S. Jaspreet Singh Karamsar',
    phone: '9310493104',
    address: 'Tri Nagar, North West Delhi',
    ward_area: 'North West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-08',
    head_office_id: 'del-ho-001',
    ward_no: 8,
    name: 'Shakur Basti',
    code: 'DEL-WD-08',
    contact_person: 'S. Rameet Singh Chadha (Smarty Chadha)',
    phone: '9811347171',
    address: '294, Sainik Vihar, Pitampura, New Delhi',
    ward_area: 'North West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-09',
    head_office_id: 'del-ho-001',
    ward_no: 9,
    name: 'Punjabi Bagh',
    code: 'DEL-WD-09',
    contact_person: 'S. Manjinder Singh Sirsa',
    phone: '9810094333',
    address: '7/77, West Punjabi Bagh, New Delhi-110026',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-10',
    head_office_id: 'del-ho-001',
    ward_no: 10,
    name: 'Guru Harkrishan Nagar',
    code: 'DEL-WD-10',
    contact_person: 'S. Surjit Singh Jitti',
    phone: '9899445555',
    address: 'Guru Harkrishan Nagar, West Delhi',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-11',
    head_office_id: 'del-ho-001',
    ward_no: 11,
    name: 'Chander Vihar',
    code: 'DEL-WD-11',
    contact_person: 'S. Nishan Singh Mann',
    phone: '9899935873',
    address: 'B-2/30, Vikas Vihar, Nilothi Extension, New Delhi-110041',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-12',
    head_office_id: 'del-ho-001',
    ward_no: 12,
    name: 'Dev Nagar',
    code: 'DEL-WD-12',
    contact_person: 'S. Jujhar Singh',
    phone: '9873324878',
    address: 'House no.4066, Gali no.37, Regarpura, Karol Bagh, New Delhi-110005',
    ward_area: 'Central Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-13',
    head_office_id: 'del-ho-001',
    ward_no: 13,
    name: 'Rajinder Nagar',
    code: 'DEL-WD-13',
    contact_person: 'S. Paramjeet Singh Chandhok',
    phone: '9810070597',
    address: '2635, Bank Street, Karol Bagh, New Delhi',
    ward_area: 'Central Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-14',
    head_office_id: 'del-ho-001',
    ward_no: 14,
    name: 'Connaught Place',
    code: 'DEL-WD-14',
    contact_person: 'S. Amarjeet Singh Pinky',
    phone: '9810021488',
    address: '2151, Kinari Bazar, Chandni Chowk, Delhi-110006',
    ward_area: 'Central Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-15',
    head_office_id: 'del-ho-001',
    ward_no: 15,
    name: 'Ramesh Nagar',
    code: 'DEL-WD-15',
    contact_person: 'S. Gurdev Singh',
    phone: '9911014141',
    address: 'Ramesh Nagar, West Delhi',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-16',
    head_office_id: 'del-ho-001',
    ward_no: 16,
    name: 'Tagore Garden',
    code: 'DEL-WD-16',
    contact_person: 'S. Bhupinder Singh Ginni',
    phone: '9873730737',
    address: 'A-7/77 Moti Nagar, New Delhi-110015',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-17',
    head_office_id: 'del-ho-001',
    ward_no: 17,
    name: 'Raghubir Nagar',
    code: 'DEL-WD-17',
    contact_person: 'S. Satinder Pal Singh Nagi',
    phone: '9910096719',
    address: 'S-221/266, Gali No.7, Vishnu Garden, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-18',
    head_office_id: 'del-ho-001',
    ward_no: 18,
    name: 'Rajouri Garden',
    code: 'DEL-WD-18',
    contact_person: 'S. Harpal Singh Kochar',
    phone: '7701926903',
    address: 'F-17, Rajouri Garden, New Delhi-110027',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-19',
    head_office_id: 'del-ho-001',
    ward_no: 19,
    name: 'Hari Nagar',
    code: 'DEL-WD-19',
    contact_person: 'S. Jaspreet Singh (Vicky Maan)',
    phone: '9810465556',
    address: 'BE-255, Gali no.2, Hari Nagar, New Delhi-110064',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-20',
    head_office_id: 'del-ho-001',
    ward_no: 20,
    name: 'Fateh Nagar',
    code: 'DEL-WD-20',
    contact_person: 'S. Amarjeet Singh (Pappu)',
    phone: '9212001906',
    address: 'C-15, Fateh Nagar, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-21',
    head_office_id: 'del-ho-001',
    ward_no: 21,
    name: 'Khayala',
    code: 'DEL-WD-21',
    contact_person: 'S. Rajinder Singh (Gughi)',
    phone: '9810728830',
    address: 'WZ-3rd29-B-126, Vishnu Garden, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-22',
    head_office_id: 'del-ho-001',
    ward_no: 22,
    name: 'Sham Nagar',
    code: 'DEL-WD-22',
    contact_person: 'S. Harjit Singh Pappa',
    phone: '9811489233',
    address: 'G-39, Vishnu Garden, Mangal Bazar, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-23',
    head_office_id: 'del-ho-001',
    ward_no: 23,
    name: 'Vishnu Garden',
    code: 'DEL-WD-23',
    contact_person: 'S. Manjit Singh Aulakh',
    phone: '9891613158',
    address: 'WZ-49H, Navyug Block, Vishnu Garden, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-24',
    head_office_id: 'del-ho-001',
    ward_no: 24,
    name: 'Ravi Nagar',
    code: 'DEL-WD-24',
    contact_person: 'S. Gurmeet Singh Bhatia',
    phone: '9212649959',
    address: 'A-12, J.J. Colony, Chowkhandi, Tilak Nagar, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-25',
    head_office_id: 'del-ho-001',
    ward_no: 25,
    name: 'Tilak Nagar',
    code: 'DEL-WD-25',
    contact_person: 'S. Daljit Singh Sarna',
    phone: '9871495180',
    address: 'D-4, Mukherjee Garden, Tilak Nagar, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-26',
    head_office_id: 'del-ho-001',
    ward_no: 26,
    name: 'Sant Garh',
    code: 'DEL-WD-26',
    contact_person: 'Sant Garh Candidate',
    phone: '9810000026',
    address: 'Sant Garh, West Delhi',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-27',
    head_office_id: 'del-ho-001',
    ward_no: 27,
    name: 'Tilak Vihar',
    code: 'DEL-WD-27',
    contact_person: 'S. Atma Singh Lubana',
    phone: '9868854548',
    address: 'C-127A, Tilak Vihar, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-28',
    head_office_id: 'del-ho-001',
    ward_no: 28,
    name: 'Guru Nanak Nagar',
    code: 'DEL-WD-28',
    contact_person: 'S. Raminder Singh Sweeta',
    phone: '9810929001',
    address: 'WZ-10/2A, New Sahibpura, MBA Nagar, Tilak Nagar, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-29',
    head_office_id: 'del-ho-001',
    ward_no: 29,
    name: 'Krishna Park',
    code: 'DEL-WD-29',
    contact_person: 'S. Jagdeep Singh Kahlon',
    phone: '9811085996',
    address: 'WZ-217, Gali No.1, Krishna Park, New Delhi-110018',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-30',
    head_office_id: 'del-ho-001',
    ward_no: 30,
    name: 'Vikas Puri',
    code: 'DEL-WD-30',
    contact_person: 'S. Inderjit Singh Monty',
    phone: '9811174950',
    address: 'Vikas Puri, West Delhi',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-31',
    head_office_id: 'del-ho-001',
    ward_no: 31,
    name: 'Uttam Nagar',
    code: 'DEL-WD-31',
    contact_person: 'S. Ramanjot Singh Meeta',
    phone: '9654919065',
    address: 'A-811, Pankha Road, Uttam Nagar, Delhi-110059',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-32',
    head_office_id: 'del-ho-001',
    ward_no: 32,
    name: 'Janak Puri',
    code: 'DEL-WD-32',
    contact_person: 'S. Gurmeet Singh Tinku',
    phone: '8130041335',
    address: 'Janak Puri, West Delhi',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-33',
    head_office_id: 'del-ho-001',
    ward_no: 33,
    name: 'Shiv Nagar',
    code: 'DEL-WD-33',
    contact_person: 'S. Ramandeep Singh Thappar',
    phone: '9818103053',
    address: 'WZ-530, Gali No. 27, Jail Road, Shiv Nagar, New Delhi-110058',
    ward_area: 'West Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-34',
    head_office_id: 'del-ho-001',
    ward_no: 34,
    name: 'Sarita Vihar',
    code: 'DEL-WD-34',
    contact_person: 'S. Gurpreet Singh Jassa',
    phone: '9810053253',
    address: 'B-18, Flat no.101, Ground Floor, Viskarma Colony, New Delhi-110011',
    ward_area: 'South East Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-35',
    head_office_id: 'del-ho-001',
    ward_no: 35,
    name: 'Lajpat Nagar',
    code: 'DEL-WD-35',
    contact_person: 'S. Paramjit Singh Bhatia',
    phone: '9873800238',
    address: 'I83-84, Lajpat Nagar-1, New Delhi-110024',
    ward_area: 'South Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-36',
    head_office_id: 'del-ho-001',
    ward_no: 36,
    name: 'Safdarjung Enclave',
    code: 'DEL-WD-36',
    contact_person: 'S. Kuldeep Singh Sawhney',
    phone: '9711313138',
    address: '165-Sarojini Nagar, New Delhi',
    ward_area: 'South Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-37',
    head_office_id: 'del-ho-001',
    ward_no: 37,
    name: 'Malviya Nagar',
    code: 'DEL-WD-37',
    contact_person: 'S. Onkar Singh Raja',
    phone: '9891164312',
    address: 'G-3/11, Malviya Nagar, Near Krishna Mandir, New Delhi-110017',
    ward_area: 'South Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-38',
    head_office_id: 'del-ho-001',
    ward_no: 38,
    name: 'Greater Kailash',
    code: 'DEL-WD-38',
    contact_person: 'S. Charanjit Singh',
    phone: '9717970696',
    address: 'House no.204, GHPS Campus, Vasant Vihar, New Delhi',
    ward_area: 'South Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-39',
    head_office_id: 'del-ho-001',
    ward_no: 39,
    name: 'Kalka Ji',
    code: 'DEL-WD-39',
    contact_person: 'S. Harmit Singh Kalka',
    phone: '9811460300',
    address: 'House No. 7, Lane W8A, Sainik Farms, New Delhi-110062',
    ward_area: 'South Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-40',
    head_office_id: 'del-ho-001',
    ward_no: 40,
    name: 'Jangpura',
    code: 'DEL-WD-40',
    contact_person: 'S. Jasmir Singh (Sunny Massi)',
    phone: '9711713313',
    address: '722, 2nd Floor Opp. Gurdwara Bala Sahib, Sunlight Colony 1, Ashram, Delhi-110014',
    ward_area: 'South East Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-41',
    head_office_id: 'del-ho-001',
    ward_no: 41,
    name: 'Navin Shahdara',
    code: 'DEL-WD-41',
    contact_person: 'S. Parvinder Singh (Lucky)',
    phone: '9599908208',
    address: 'Navin Shahdara, East Delhi',
    ward_area: 'East Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-42',
    head_office_id: 'del-ho-001',
    ward_no: 42,
    name: 'Dilshad Garden',
    code: 'DEL-WD-42',
    contact_person: 'S. Balbir Singh',
    phone: '9868855555',
    address: 'C-145, Vivek Vihar, Delhi-110095',
    ward_area: 'East Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-43',
    head_office_id: 'del-ho-001',
    ward_no: 43,
    name: 'Vivek Vihar',
    code: 'DEL-WD-43',
    contact_person: 'S. Jasmain Singh Noni',
    phone: '9999009936',
    address: '252/4, Street No., Bhola Nath Nagar, Delhi-110032',
    ward_area: 'East Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-44',
    head_office_id: 'del-ho-001',
    ward_no: 44,
    name: 'Geeta Colony',
    code: 'DEL-WD-44',
    contact_person: 'Gurmeet Singh Bedi',
    phone: '9810000044',
    address: 'Geeta Colony, East Delhi',
    ward_area: 'East Delhi',
    is_active: true,
    status_label: 'Active',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-45',
    head_office_id: 'del-ho-001',
    ward_no: 45,
    name: 'Khureji Khas',
    code: 'DEL-WD-45',
    contact_person: 'S. Jatinder Pal Singh Goldy',
    phone: '9810257677',
    address: '93/2, Guru Angad Nagar East, 1st floor, Gali No.8, behind Sai Mandir, Delhi',
    ward_area: 'East Delhi',
    is_active: true,
    status_label: 'Lost',
    head_office: DELHI_HEAD_OFFICE,
  },
  {
    id: 'ward-del-46',
    head_office_id: 'del-ho-001',
    ward_no: 46,
    name: 'Preet Vihar',
    code: 'DEL-WD-46',
    contact_person: 'S. Bupinder Singh Bhullar',
    phone: '9811070501',
    address: 'B-141, Pandav Nagar, Opp. Mother Dairy, Delhi-110092',
    ward_area: 'East Delhi',
    is_active: true,
    status_label: 'Won',
    head_office: DELHI_HEAD_OFFICE,
  },

  // Noida Starter Branches
  {
    id: 'ward-noi-101',
    head_office_id: 'noi-ho-002',
    ward_no: 101,
    name: 'Noida Sector 62',
    code: 'NOI-BR-01',
    contact_person: 'Noida Hub Operations',
    phone: '9810000101',
    address: 'Sector 62 Institutional Area, Noida',
    ward_area: 'Sector 62',
    is_active: true,
    head_office: NOIDA_HEAD_OFFICE,
  },
  {
    id: 'ward-noi-102',
    head_office_id: 'noi-ho-002',
    ward_no: 102,
    name: 'Noida Sector 18',
    code: 'NOI-BR-02',
    contact_person: 'Noida Commercial Market',
    phone: '9810000102',
    address: 'Sector 18 Commercial Market, Noida',
    ward_area: 'Sector 18',
    is_active: true,
    head_office: NOIDA_HEAD_OFFICE,
  },

  // Gurgaon Starter Branches
  {
    id: 'ward-ggn-201',
    head_office_id: 'ggn-ho-003',
    ward_no: 201,
    name: 'Cyber City',
    code: 'GGN-BR-01',
    contact_person: 'Gurgaon DLF Cyber City Hub',
    phone: '9810000201',
    address: 'DLF Cyber City Phase II, Gurugram',
    ward_area: 'DLF Phase II',
    is_active: true,
    head_office: GURGAON_HEAD_OFFICE,
  },
  {
    id: 'ward-ggn-202',
    head_office_id: 'ggn-ho-003',
    ward_no: 202,
    name: 'MG Road',
    code: 'GGN-BR-02',
    contact_person: 'MG Road Hub Manager',
    phone: '9810000202',
    address: 'MG Road Commercial Hub, Gurugram',
    ward_area: 'MG Road',
    is_active: true,
    head_office: GURGAON_HEAD_OFFICE,
  },
];

module.exports = {
  DELHI_HEAD_OFFICE,
  NOIDA_HEAD_OFFICE,
  GURGAON_HEAD_OFFICE,
  ALL_HEAD_OFFICES,
  ALL_WARDS,
};
